apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongo-init-script
              mountPath: /docker-entrypoint-initdb.d
  
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: hello
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: secret
      volumes:
        - name: mongo-init-script
          configMap:
            name: mongo-init-config
